# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'notepad_ui.ui'
##
## Created by: Qt User Interface Compiler version 6.2.4
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QMainWindow, QMenu,
    QMenuBar, QPlainTextEdit, QSizePolicy, QStatusBar,
    QWidget)

class Ui_NotePad(object):
    def setupUi(self, NotePad):
        if not NotePad.objectName():
            NotePad.setObjectName(u"NotePad")
        NotePad.resize(1280, 720)
        self.action_new = QAction(NotePad)
        self.action_new.setObjectName(u"action_new")
        self.action_open = QAction(NotePad)
        self.action_open.setObjectName(u"action_open")
        self.action_save = QAction(NotePad)
        self.action_save.setObjectName(u"action_save")
        self.action_save_as = QAction(NotePad)
        self.action_save_as.setObjectName(u"action_save_as")
        self.action_exit = QAction(NotePad)
        self.action_exit.setObjectName(u"action_exit")
        self.action_undo = QAction(NotePad)
        self.action_undo.setObjectName(u"action_undo")
        self.action_cut = QAction(NotePad)
        self.action_cut.setObjectName(u"action_cut")
        self.action_copy = QAction(NotePad)
        self.action_copy.setObjectName(u"action_copy")
        self.action_paste = QAction(NotePad)
        self.action_paste.setObjectName(u"action_paste")
        self.action_del = QAction(NotePad)
        self.action_del.setObjectName(u"action_del")
        self.action_find = QAction(NotePad)
        self.action_find.setObjectName(u"action_find")
        self.action_next_find = QAction(NotePad)
        self.action_next_find.setObjectName(u"action_next_find")
        self.action_change = QAction(NotePad)
        self.action_change.setObjectName(u"action_change")
        self.action_move = QAction(NotePad)
        self.action_move.setObjectName(u"action_move")
        self.action_all = QAction(NotePad)
        self.action_all.setObjectName(u"action_all")
        self.action_time = QAction(NotePad)
        self.action_time.setObjectName(u"action_time")
        self.action_redo = QAction(NotePad)
        self.action_redo.setObjectName(u"action_redo")
        self.action = QAction(NotePad)
        self.action.setObjectName(u"action")
        self.action.setCheckable(True)
        self.action.setChecked(True)
        self.action_2 = QAction(NotePad)
        self.action_2.setObjectName(u"action_2")
        self.action_4 = QAction(NotePad)
        self.action_4.setObjectName(u"action_4")
        self.action_4.setCheckable(True)
        self.action_4.setChecked(True)
        self.action_5 = QAction(NotePad)
        self.action_5.setObjectName(u"action_5")
        self.action_6 = QAction(NotePad)
        self.action_6.setObjectName(u"action_6")
        self.action_7 = QAction(NotePad)
        self.action_7.setObjectName(u"action_7")
        self.action_8 = QAction(NotePad)
        self.action_8.setObjectName(u"action_8")
        self.action_9 = QAction(NotePad)
        self.action_9.setObjectName(u"action_9")
        self.action_F = QAction(NotePad)
        self.action_F.setObjectName(u"action_F")
        self.action_3 = QAction(NotePad)
        self.action_3.setObjectName(u"action_3")
        self.centralwidget = QWidget(NotePad)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.grid_layout = QGridLayout()
        self.grid_layout.setObjectName(u"grid_layout")
        self.grid_layout.setVerticalSpacing(6)
        self.plainTextEdit = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName(u"plainTextEdit")

        self.grid_layout.addWidget(self.plainTextEdit, 0, 0, 1, 1)


        self.gridLayout.addLayout(self.grid_layout, 0, 0, 1, 1)

        NotePad.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(NotePad)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1280, 22))
        self.menu_file = QMenu(self.menubar)
        self.menu_file.setObjectName(u"menu_file")
        self.menu_help = QMenu(self.menubar)
        self.menu_help.setObjectName(u"menu_help")
        self.menu_view = QMenu(self.menubar)
        self.menu_view.setObjectName(u"menu_view")
        self.menu = QMenu(self.menu_view)
        self.menu.setObjectName(u"menu")
        self.menu_form = QMenu(self.menubar)
        self.menu_form.setObjectName(u"menu_form")
        self.menu_edit = QMenu(self.menubar)
        self.menu_edit.setObjectName(u"menu_edit")
        NotePad.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(NotePad)
        self.statusbar.setObjectName(u"statusbar")
        NotePad.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_edit.menuAction())
        self.menubar.addAction(self.menu_form.menuAction())
        self.menubar.addAction(self.menu_view.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())
        self.menu_file.addAction(self.action_new)
        self.menu_file.addAction(self.action_open)
        self.menu_file.addAction(self.action_save)
        self.menu_file.addAction(self.action_save_as)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_exit)
        self.menu_help.addAction(self.action_5)
        self.menu_help.addAction(self.action_F)
        self.menu_help.addSeparator()
        self.menu_help.addAction(self.action_6)
        self.menu_view.addAction(self.menu.menuAction())
        self.menu_view.addAction(self.action_3)
        self.menu.addAction(self.action_7)
        self.menu.addAction(self.action_8)
        self.menu.addAction(self.action_9)
        self.menu_form.addAction(self.action)
        self.menu_form.addAction(self.action_2)
        self.menu_edit.addAction(self.action_undo)
        self.menu_edit.addAction(self.action_redo)
        self.menu_edit.addSeparator()
        self.menu_edit.addAction(self.action_cut)
        self.menu_edit.addAction(self.action_copy)
        self.menu_edit.addAction(self.action_paste)
        self.menu_edit.addAction(self.action_del)
        self.menu_edit.addSeparator()
        self.menu_edit.addAction(self.action_find)
        self.menu_edit.addAction(self.action_next_find)
        self.menu_edit.addAction(self.action_change)
        self.menu_edit.addAction(self.action_move)
        self.menu_edit.addSeparator()
        self.menu_edit.addAction(self.action_all)
        self.menu_edit.addAction(self.action_time)

        self.retranslateUi(NotePad)

        QMetaObject.connectSlotsByName(NotePad)
    # setupUi

    def retranslateUi(self, NotePad):
        NotePad.setWindowTitle(QCoreApplication.translate("NotePad", u"\uba54\ubaa8\uc7a5", None))
        self.action_new.setText(QCoreApplication.translate("NotePad", u"\uc0c8\ub85c \ub9cc\ub4e4\uae30", None))
#if QT_CONFIG(shortcut)
        self.action_new.setShortcut(QCoreApplication.translate("NotePad", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.action_open.setText(QCoreApplication.translate("NotePad", u"\uc5f4\uae30", None))
#if QT_CONFIG(shortcut)
        self.action_open.setShortcut(QCoreApplication.translate("NotePad", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.action_save.setText(QCoreApplication.translate("NotePad", u"\uc800\uc7a5", None))
#if QT_CONFIG(shortcut)
        self.action_save.setShortcut(QCoreApplication.translate("NotePad", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.action_save_as.setText(QCoreApplication.translate("NotePad", u"\ub2e4\ub978 \uc774\ub984\uc73c\ub85c \uc800\uc7a5", None))
#if QT_CONFIG(shortcut)
        self.action_save_as.setShortcut(QCoreApplication.translate("NotePad", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.action_exit.setText(QCoreApplication.translate("NotePad", u"\ub05d\ub0b4\uae30", None))
        self.action_undo.setText(QCoreApplication.translate("NotePad", u"\uc2e4\ud589 \ucde8\uc18c", None))
#if QT_CONFIG(shortcut)
        self.action_undo.setShortcut(QCoreApplication.translate("NotePad", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.action_cut.setText(QCoreApplication.translate("NotePad", u"\uc798\ub77c\ub0b4\uae30", None))
#if QT_CONFIG(shortcut)
        self.action_cut.setShortcut(QCoreApplication.translate("NotePad", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.action_copy.setText(QCoreApplication.translate("NotePad", u"\ubcf5\uc0ac", None))
#if QT_CONFIG(shortcut)
        self.action_copy.setShortcut(QCoreApplication.translate("NotePad", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.action_paste.setText(QCoreApplication.translate("NotePad", u"\ubd99\uc5ec\ub123\uae30", None))
#if QT_CONFIG(shortcut)
        self.action_paste.setShortcut(QCoreApplication.translate("NotePad", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.action_del.setText(QCoreApplication.translate("NotePad", u"\uc0ad\uc81c", None))
#if QT_CONFIG(shortcut)
        self.action_del.setShortcut(QCoreApplication.translate("NotePad", u"Del", None))
#endif // QT_CONFIG(shortcut)
        self.action_find.setText(QCoreApplication.translate("NotePad", u"\ucc3e\uae30", None))
#if QT_CONFIG(shortcut)
        self.action_find.setShortcut(QCoreApplication.translate("NotePad", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.action_next_find.setText(QCoreApplication.translate("NotePad", u"\ub2e4\uc74c \ucc3e\uae30", None))
#if QT_CONFIG(shortcut)
        self.action_next_find.setShortcut(QCoreApplication.translate("NotePad", u"F3", None))
#endif // QT_CONFIG(shortcut)
        self.action_change.setText(QCoreApplication.translate("NotePad", u"\ubc14\uafb8\uae30", None))
#if QT_CONFIG(shortcut)
        self.action_change.setShortcut(QCoreApplication.translate("NotePad", u"Ctrl+H", None))
#endif // QT_CONFIG(shortcut)
        self.action_move.setText(QCoreApplication.translate("NotePad", u"\uc774\ub3d9", None))
#if QT_CONFIG(shortcut)
        self.action_move.setShortcut(QCoreApplication.translate("NotePad", u"Ctrl+G", None))
#endif // QT_CONFIG(shortcut)
        self.action_all.setText(QCoreApplication.translate("NotePad", u"\ubaa8\ub450 \uc120\ud0dd", None))
#if QT_CONFIG(shortcut)
        self.action_all.setShortcut(QCoreApplication.translate("NotePad", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.action_time.setText(QCoreApplication.translate("NotePad", u"\uc2dc\uac04/\ub0a0\uc9dc", None))
#if QT_CONFIG(shortcut)
        self.action_time.setShortcut(QCoreApplication.translate("NotePad", u"F5", None))
#endif // QT_CONFIG(shortcut)
        self.action_redo.setText(QCoreApplication.translate("NotePad", u"\ub2e4\uc2dc \uc2e4\ud589", None))
#if QT_CONFIG(shortcut)
        self.action_redo.setShortcut(QCoreApplication.translate("NotePad", u"Ctrl+Y", None))
#endif // QT_CONFIG(shortcut)
        self.action.setText(QCoreApplication.translate("NotePad", u"\uc790\ub3d9 \uc904 \ubc14\uafc8", None))
        self.action_2.setText(QCoreApplication.translate("NotePad", u"\uae00\uaf34", None))
        self.action_4.setText(QCoreApplication.translate("NotePad", u"\uc0c1\ud0dc \ud45c\uc2dc\uc904", None))
        self.action_5.setText(QCoreApplication.translate("NotePad", u"\ub3c4\uc6c0\ub9d0 \ubcf4\uae30", None))
        self.action_6.setText(QCoreApplication.translate("NotePad", u"\ub3c4\uc6c0\ub9d0 \uc815\ubcf4", None))
        self.action_7.setText(QCoreApplication.translate("NotePad", u"\ud655\ub300", None))
        self.action_8.setText(QCoreApplication.translate("NotePad", u"\ucd95\uc18c", None))
        self.action_9.setText(QCoreApplication.translate("NotePad", u"\ud655\ub300\ud558\uae30/\ucd95\uc18c\ud558\uae30 \uae30\ubcf8\uac12 \ubcf5\uc6d0", None))
        self.action_F.setText(QCoreApplication.translate("NotePad", u"\ud53c\ub4dc\ubc31 \ubcf4\ub0b4\uae30(&F)\n"
"\n"
"", None))
        self.action_3.setText(QCoreApplication.translate("NotePad", u"\uc0c1\ud0dc \ud45c\uc2dc\uc904", None))
        self.menu_file.setTitle(QCoreApplication.translate("NotePad", u"\ud30c\uc77c(F)", None))
        self.menu_help.setTitle(QCoreApplication.translate("NotePad", u"\ub3c4\uc6c0\ub9d0", None))
        self.menu_view.setTitle(QCoreApplication.translate("NotePad", u"\ubcf4\uae30", None))
        self.menu.setTitle(QCoreApplication.translate("NotePad", u" \ud655\ub300\ud558\uae30/\ucd95\uc18c\ud558\uae30", None))
        self.menu_form.setTitle(QCoreApplication.translate("NotePad", u"\uc11c\uc2dd", None))
        self.menu_edit.setTitle(QCoreApplication.translate("NotePad", u"\ud3b8\uc9d1", None))
    # retranslateUi

